import type { Metadata } from "next";
import { Poppins, Readex_Pro } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainProvider from "@/rtk/MainProvider";
import { cookies } from "next/headers";
import { AuthProvider } from "@/context/AuthContext";
import ResponsiveToaster from "@/components/ResponsiveToaster/ResponsiveToaster";

export const metadata: Metadata = {
  title: "Mongiz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const token = (await cookies()).get("token")?.value || null;
  const role = (await cookies()).get("roles")?.value || null;
  const userCookie = (await cookies()).get("user")?.value;

  let emailConfirmed = false;

  if (userCookie) {
    try {
      const user = JSON.parse(userCookie);
      emailConfirmed = user?.emailConfirmed ?? false;
    } catch {
      emailConfirmed = false;
    }
  }
  const currency = (await cookies()).get("currency")?.value || "USD";

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} data-scroll-behavior="smooth">
      <body
        className={`font-expo`}
      >
        <ResponsiveToaster />
        <NextIntlClientProvider messages={messages}>
          <AuthProvider initialToken={token} initialRole={role} initialEmailConfirmed={emailConfirmed} >
            <MainProvider
              lang={locale ?? "en"}
              currency={currency}
            >
              {children}
            </MainProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
